language: go

go:
  - 1.14.7

env: GO111MODULE=on

branches:
  except:
    - slave

arch:
  - amd64

os:
  - windows
  - osx
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make ; fi

script:
  - make test
  - make
  - make clean

#after_success:
#  - make
#
#deploy:
#  provider: releases
#  api_key: $GITHUB_OAUTH_TOKEN
#  file_glob: true
#  file: builds/*
#  skip_cleanup: true
#  prerelease: true
#  on:
#    repo: BennyThink/KeepMeBot
#    branch: master
#
#after_deploy:
#  - make clean