language: go

go:
  - 1.14.7

env: GO111MODULE=on

branches:
  except:
    - slave

arch:
  - amd64
  - arm64

os:
  - windows
  - osx
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make ; fi

script:
  - make
  - make clean
  - make test
